server:
  address: 0.0.0.0
  port: ${APP_PORT:8080}
spring:
  application:
    name: manageable-redis-topics
  redis:
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:12345678}
    port: ${REDIS_PORT:16379}


app:
  manageable:
    redis:
      topics: redis.manageable.topic


